config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"}
  root to: "homes#top" 
  get '/about' => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :equipments, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :books, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :rules, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :urabeyas, only: [:index, :create, :edit, :update, :destroy, :new]

end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_one_attached :image
  def get_image(width, height)
    unless image.attached?
     file_path = Rails.root.join('app/assets/images/noimage.png')
     image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
   image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  before_action :authenticate_admin!, except: [:index]
  
  def new
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.save
    redirect_to equipments_path
  end

  def index
    @equipments = Equipment.all
    @equipment = Equipment.new
  end

  def edit
    @equipment = Equipment.find(params[:id])
  end

  def update
    @equipment = Equipment.find(params[:id])
    @equipment.update(equipment_params)
    redirect_to equipments_path
  end

  def destroy
    equipment = Equipment.find(params[:id])
    equipment.destroy
    redirect_to equipments_path
  end

  private
  def equipment_params
    params.require(:equipment).permit(:name, :image, :detail)
  end

end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipments/edit.html.erb
<div class="container">
 <h1>設備編集</h1>
 <%= form_with model: @equipment,url:equipment_path(@equipment.id),method: :patch do |f| %>
  <h4>設備名</h4>
  <%= f.text_field :name %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>

  <h4>詳細</h4>
  <%= f.text_area :detail %> 
  <%= f.submit 'Update' %>
  <%= link_to "Back", equipments_path %>

 <% end %>
</div>

app/views/equipments/index.html.erb
<div class="container pt-4" style="padding-bottom: 100px;">
  <h1>設備</h1>
  <p>角部屋には便利なものがたくさんあります。ぜひ使いこなしてくださいね。利用時のルールについては<%= link_to "こちら", rules_path %>をご覧ください。</p>
    <% if admin_signed_in? %>
      <%= link_to "追加", new_equipment_path(@equipment.id) %>
    <% end %>
  <div class="d-flex flex-wrap">
    <% @equipments.each do |equipment| %>
      <div class="m-4">
          <div>
          <%= image_tag equipment.get_image(200,200) %>
          </div>
          <div><h5><%= equipment.name %></h5></div>
          <div style="width: 270px;"><%= safe_join(equipment.detail.split("\n"),tag(:br)) %></div>
        

        <% if admin_signed_in? %>
          <%= link_to "削除", equipment_path(equipment.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <%= link_to "編集", edit_equipment_path(equipment.id) %>
        <% end %>
      </div>  
    <% end %>
  </div>
</div>

app/views/equipments/new.html.erb
<div class="container">
  <%= form_with model: @equipment, url: equipments_path do |f| %>
    <h4>設備名</h4>
    <%= f.text_field :name %>

    <h4>画像</h4>
    <%= f.file_field :image, accept: "image/*" %>

    <h4>詳細</h4>
    <%= f.text_area :detail %> 
    <%= f.submit '投稿' %>
  <% end %>
</div>