config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"}
  root to: "homes#top" 
  get '/about' => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :equipments, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :books, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :rules, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :urabeyas, only: [:index, :create, :edit, :update, :destroy, :new]

end

app/models/urabeya.rb
class Urabeya < ApplicationRecord
    validates :class_url, presence: true
end

app/controllers/urabeyas_controller.rb
class UrabeyasController < ApplicationController
  before_action :authenticate_admin!, except: [:index]

  def new
    @urabeya = Urabeya.new
  end
  
  def create
    @urabeya = Urabeya.new(urabeya_params)
    if @urabeya.save
      redirect_to urabeyas_path
    else
      render :new
    end
  end

  def index
    @urabeyas = Urabeya.all.order(:number)
    @urabeya = Urabeya.new
  end
  
  def edit
    @urabeya = Urabeya.find(params[:id])
  end

  def update
    @urabeya = Urabeya.find(params[:id])
    if @urabeya.update(urabeya_params)
      redirect_to urabeyas_path
    else
      render :edit
    end
  end
  
  def destroy
    @urabeya = Urabeya.find(params[:id])
    @urabeya.destroy
    redirect_to urabeyas_path
  end
  
  private
  def urabeya_params
    params.require(:urabeya).permit(:title, :teacher, :number, :class_name, :class_url)
  end
end

app/helpers/urabeyas_helper.rb
module UrabeyasHelper
end

app/views/urabeyas/edit.html.erb
<div class="container">
  <% if @urabeya.errors.any? %>
    <%= @urabeya.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% @urabeya.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @urabeya, url: urabeya_path(@urabeya.id), method: :patch do |f| %>
    <h4>授業名</h4>
    <%= f.text_area :title %>

    <h4>先生</h4>
    <%= f.text_field :teacher %>

    <h4>講義動画タイトル</h4>
    <%= f.text_area :class_name %>
  
    <h4>URL</h4>
    <%= f.text_field :class_url %>
  
    <h4>整理番号</h4>
    <%= f.text_field :number %>
  
    <%= f.submit '投稿' %>
  <% end %>
</div>

app/views/urabeyas/index.html.erb
<div class="container pt-4" style="padding-bottom: 100px;">
    <p>こちらには先生方から頂いた講義動画を載せています。有効に活用しましょう。</p>
    <% if admin_signed_in? %>
      <%= link_to "追加", new_urabeya_path(@urabeya.id) %>
    <% end %>
  <div class="mx-5">
    <% @urabeyas.each do |urabeya| %>
      <% if urabeya.title.present? %>
        <div class="row mt-5">
          <h5><%= urabeya.title %><span class="h6 ml-2 text-nowrap"><%= urabeya.teacher %></span></h5>
        </div>
      <% else %>
      <% end %>
      <div class="row mt-1">
        <div class="ml-4 col-md-4" style="height: 20px;">
          <p class="text-nowrap"><%= urabeya.class_name %></p>
        </div>
        <div class="ml-4 mb-2 col-md-6" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
          <%= Rinku.auto_link(urabeya.class_url, :all, 'target="_blank"').html_safe %>
        </div>
      </div>
      
      <div>   
        <% if admin_signed_in? %>
          <%= urabeya.number %>
            <%= link_to "削除", urabeya_path(urabeya.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
            <%= link_to "編集", edit_urabeya_path(urabeya.id) %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/urabeyas/new.html.erb
<div class="container">
  <% if @urabeya.errors.any? %>
    <%= @urabeya.errors.count %> error prohibited this obj from being saved:
    <ul>
      <% @urabeya.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @urabeya, url: urabeyas_path do |f| %>
    <h4>授業名</h4>
    <%= f.text_area :title %>

    <h4>先生</h4>
    <%= f.text_field :teacher %>

    <h4>講義動画タイトル</h4>
    <%= f.text_area :class_name %>
    
    <h4>URL</h4>
    <%= f.text_field :class_url %>
  
    <h4>整理番号</h4>
    <%= f.text_field :number %>
  
    <%= f.submit '投稿' %>
  <% end %>
</div>