config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"}
  root to: "homes#top" 
  get '/about' => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :equipments, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :books, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :rules, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :urabeyas, only: [:index, :create, :edit, :update, :destroy, :new]

end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_admin!, except: [:index]
  
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to books_path
  end

  def index
    @books = Book.all.order(:number)
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to books_path
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:category, :number, :title, :author, :publisher, :date, :detail)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>蔵書編集</h1>
<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
  <h4>カテゴリー</h4>
  <%= f.text_field :category %>

  <h4>整理番号</h4>
  <%= f.text_field :number %>

  <h4>書名</h4>
  <%= f.text_area :title %>
  
  <h4>著者名</h4>
  <%= f.text_field :author %>
  
  <h4>出版社</h4>
  <%= f.text_field :publisher %>
  
  <h4>購入日</h4>
  <%= f.text_field :date %>
  
  <h4>備考</h4>
  <%= f.text_area :detail %>
  
  <%= f.submit 'Update' %>
  <%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<div class="container pt-4" style="padding-bottom: 100px;">
  <h1>蔵書</h1>
    <p>角部屋にある蔵書一覧です。マナーを守って使いましょう。利用時のルールについては<%= link_to "こちら", rules_path %>をご覧ください。</p>
    <% if admin_signed_in? %>
      <%= link_to "追加", new_book_path(@book.id) %>
    <% end %>
  <div style="overflow-x: scroll;">
    <table class="table table-bordered" style="table-layout:fixed;">
      <tr style="background-color: rgba(211,211,211,0.5);">
        <th style="width: 160px;">分野</th>
        <th style="width: 100px;">整理番号</th>
        <th style="width: 300px;">書名</th>
        <th style="width: 150px;">著者名</th>
        <th style="width: 100px;">出版社</th>
        <th style="width: 100px;">購入日</th>
        <th style="width: 200px;">備考</th>
        <% if admin_signed_in? %>
          <th style="width: 100px;"></th>
        <% end %>
      </tr>

　  　<% @books.each do |book| %>
      <tr>
        <td><%= book.category %></td>
        <td><%= book.number %></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.date %></td>
        <td><%= book.detail %></td>
        
        <% if admin_signed_in? %>
          <td>
            <%= link_to "削除", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
            <%= link_to "編集", edit_book_path(book.id) %>
          </td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/books/new.html.erb
<%= form_with model: @book, url: books_path do |f| %>
  <h4>カテゴリー</h4>
  <%= f.text_field :category %>

  <h4>整理番号</h4>
  <%= f.text_field :number %>

  <h4>書名</h4>
  <%= f.text_area :title %>
  
  <h4>著者名</h4>
  <%= f.text_field :author %>
  
  <h4>出版社</h4>
  <%= f.text_field :publisher %>
  
  <h4>購入日</h4>
  <%= f.text_field :date %>
  
  <h4>備考</h4>
  <%= f.text_area :detail %>
  
  <%= f.submit '投稿' %>
<% end %>