config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"}
  root to: "homes#top" 
  get '/about' => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :equipments, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :books, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :rules, only: [:index, :create, :edit, :update, :destroy, :new]
  resources :urabeyas, only: [:index, :create, :edit, :update, :destroy, :new]

end

app/models/rule.rb
class Rule < ApplicationRecord
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :authenticate_admin!, except: [:index]
  
  def new
    @rule = Rule.new
  end
  
  def create
    @rule = Rule.new(rule_params)
    @rule.save
    redirect_to rules_path
  end

  def index
    @rules = Rule.all
    @rule = Rule.new
  end

  def edit
    @rule = Rule.find(params[:id])
  end
  
  def update
    @rule = Rule.find(params[:id])
    @rule.update(rule_params)
    redirect_to rules_path
  end
  
  def destroy
    rule = Rule.find(params[:id])
    rule.destroy
    redirect_to rules_path
  end
  
  private
  def rule_params
    params.require(:rule).permit(:title, :body)
  end
  
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/edit.html.erb
<div class="container">
  <%= form_with model: @rule, url: rule_path(@rule.id), method: :patch do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>内容</h4>
    <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  <% end %>
</>

app/views/rules/index.html.erb
<div class="container pt-4"style="padding-bottom: 100px;">
  <h1>使い方・ルール</h1>
    <% if admin_signed_in? %>
      <%= link_to "追加", new_rule_path(@rule.id) %>
    <% end %>
    <% @rules.each do |rule| %>
      <div class="m-3">
        <h4><span style="background: linear-gradient(transparent 60%, #ffdead 0%); padding: 0 10px;"><%= rule.title %></span></h4>
      </div>
      <div class="mx-5"><%= safe_join(rule.body.split("\n"),tag(:br)) %></div>
        
        <% if admin_signed_in? %>
            <%= link_to "削除", rule_path(rule.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
            <%= link_to "編集", edit_rule_path(rule.id) %>
        <% end %>
    <% end %>

</div>

app/views/rules/new.html.erb
<div class="container">
  <h1>ルール追加</h1>
  <%= form_with model: @rule, url: rules_path do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
  
    <h4>内容</h4>
    <%= f.text_area :body %>
  
    <%= f.submit '投稿' %>
  <% end %>
</div>